package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_ASSIGNMENT_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u51/3951/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Monday, June 8, 2015 7:28:45 PM PDT
*/

public interface ID_ASSIGNMENT_POLICY_ID
{

  /**
  	 * The value representing ID_ASSIGNMENT_POLICY_ID.
  	 */
  public static final int value = (int)(19L);
}
