package org.omg.PortableServer;


/**
* org/omg/PortableServer/ServantActivator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u51/3951/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Monday, June 8, 2015 7:28:45 PM PDT
*/


/**
	 * When the POA has the RETAIN policy it uses servant 
	 * managers that are ServantActivators. 
	 */
public interface ServantActivator extends ServantActivatorOperations, org.omg.PortableServer.ServantManager, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServantActivator
